Document: libsilk
Title: Debian libsilk Manual
Author: <insert document author here>
Abstract: This manual describes what libsilk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsilk/libsilk.sgml.gz

Format: postscript
Files: /usr/share/doc/libsilk/libsilk.ps.gz

Format: text
Files: /usr/share/doc/libsilk/libsilk.text.gz

Format: HTML
Index: /usr/share/doc/libsilk/html/index.html
Files: /usr/share/doc/libsilk/html/*.html
